using System.Text;

namespace HelpersSidecar.Application;

/// <summary>
/// Composes <c>AI_LEVEL_REPORT v1</c> markdown for one or more
/// scored skills, plus the project aggregate. Plan-10 wires this
/// directly to <c>File.WriteAllText</c>; Plan-11 will retrofit
/// through <c>IArtefactWriter</c> once the artefact registry
/// lands.
/// </summary>
public sealed class AiLevelReportWriter
{
    public AiLevelReportPayload Compose(
        string scope,
        IReadOnlyList<AiLevelSkillScore> skills,
        DateTimeOffset generatedAtUtc)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# AI level report — {scope}");
        sb.AppendLine();
        sb.AppendLine("> Auto-generated by `/ai-level`. Per `BR-PROCESS-013` this is a");
        sb.AppendLine("> schema-versioned report. Re-run the skill to refresh.");
        sb.AppendLine();
        sb.AppendLine($"AI_LEVEL_REPORT v1 — generated {generatedAtUtc:yyyy-MM-ddTHH:mm:ssZ}");
        sb.AppendLine($"Scope: {scope}");
        sb.AppendLine($"Skills assessed: {skills.Count}");
        sb.AppendLine();

        AppendPerSkillTable(sb, skills);
        AppendPerSkillEvidence(sb, skills);
        AppendProjectAggregate(sb, skills);
        AppendCrossCuttingFindings(sb, skills);

        sb.AppendLine();
        sb.AppendLine("## How to act on this report");
        sb.AppendLine();
        sb.AppendLine("- Pick a skill with a weak dimension. Read its evidence below.");
        sb.AppendLine("- Open the SKILL.md; the evidence string names the missing field or pattern.");
        sb.AppendLine("- The fix is usually < 10 lines of frontmatter or body.");
        sb.AppendLine("- Re-run `/ai-level <skill>` to confirm the score improved.");

        return new AiLevelReportPayload(sb.ToString(), skills);
    }

    private static void AppendPerSkillTable(StringBuilder sb, IReadOnlyList<AiLevelSkillScore> skills)
    {
        sb.AppendLine("## Per-skill scores");
        sb.AppendLine();
        sb.AppendLine("| Skill | Delegation | Description | Discernment | Diligence | Total | Weakest |");
        sb.AppendLine("|---|---|---|---|---|---|---|");
        foreach (var s in skills.OrderBy(s => s.SkillName, StringComparer.Ordinal))
        {
            var del = ScoreCell(s, AiLevelDimension.Delegation);
            var dsc = ScoreCell(s, AiLevelDimension.Description);
            var dis = ScoreCell(s, AiLevelDimension.Discernment);
            var dil = ScoreCell(s, AiLevelDimension.Diligence);
            var weakest = s.WeakestDimensions.Count == 0
                ? "(none)"
                : string.Join(", ", s.WeakestDimensions);
            sb.AppendLine($"| {s.SkillName} | {del} | {dsc} | {dis} | {dil} | {s.Total}/8 | {weakest} |");
        }
        sb.AppendLine();
    }

    private static void AppendPerSkillEvidence(StringBuilder sb, IReadOnlyList<AiLevelSkillScore> skills)
    {
        sb.AppendLine("## Per-skill evidence");
        sb.AppendLine();
        foreach (var skill in skills.OrderBy(s => s.SkillName, StringComparer.Ordinal))
        {
            sb.AppendLine($"### {skill.SkillName} ({skill.Total}/8)");
            sb.AppendLine();
            foreach (var d in skill.Dimensions)
            {
                sb.AppendLine($"**{d.Dimension}: {(int)d.Score}/2**");
                foreach (var o in d.Outcomes)
                {
                    var mark = o.Passed ? "✓" : "✗";
                    sb.AppendLine($"- {mark} `{o.CheckName}` — {o.Evidence}");
                }
                sb.AppendLine();
            }
        }
    }

    private static void AppendProjectAggregate(StringBuilder sb, IReadOnlyList<AiLevelSkillScore> skills)
    {
        sb.AppendLine("## Project aggregate");
        sb.AppendLine();
        if (skills.Count == 0)
        {
            sb.AppendLine("_(no skills assessed)_");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("| Dimension | Average | Skills at 2/2 | Skills at 0/2 | Weakest example |");
        sb.AppendLine("|---|---|---|---|---|");
        foreach (var dim in Enum.GetValues<AiLevelDimension>())
        {
            // Each skill may legally lack a dimension (older reports under
            // rubric evolution). Treat absence as 0 — same effect as Absent.
            var values = skills
                .Select(s => (int?)(s.Dimensions.FirstOrDefault(d => d.Dimension == dim)?.Score) ?? 0)
                .ToList();
            var avg = values.Average();
            var strong = values.Count(v => v == 2);
            var absent = values.Count(v => v == 0);
            var weakest = skills
                .OrderBy(s => (int?)(s.Dimensions.FirstOrDefault(d => d.Dimension == dim)?.Score) ?? 0)
                .First().SkillName;
            sb.AppendLine($"| {dim} | {avg:F1} / 2 | {strong} / {skills.Count} | {absent} / {skills.Count} | {weakest} |");
        }
        sb.AppendLine();
    }

    private static void AppendCrossCuttingFindings(StringBuilder sb, IReadOnlyList<AiLevelSkillScore> skills)
    {
        sb.AppendLine("## Top cross-cutting findings");
        sb.AppendLine();
        if (skills.Count == 0)
        {
            sb.AppendLine("_(no skills assessed)_");
            return;
        }

        // Aggregate failed-check counts across skills.
        var failures = skills
            .SelectMany(s => s.Dimensions.SelectMany(d => d.Outcomes
                .Where(o => !o.Passed)
                .Select(o => new { Skill = s.SkillName, Dimension = d.Dimension, o.CheckName, o.Evidence })))
            .GroupBy(x => x.CheckName)
            .OrderByDescending(g => g.Count())
            .Take(3)
            .ToList();

        if (failures.Count == 0)
        {
            sb.AppendLine("_(no failures across the assessed skills — full marks)_");
            return;
        }

        var i = 1;
        foreach (var g in failures)
        {
            var skillsList = string.Join(", ", g.Select(x => x.Skill).Distinct().OrderBy(s => s, StringComparer.Ordinal));
            sb.AppendLine($"{i}. **{g.Key}** — {g.Count()} skill(s) affected: {skillsList}");
            i++;
        }
    }

    private static string ScoreCell(AiLevelSkillScore s, AiLevelDimension d)
    {
        var dim = s.Dimensions.FirstOrDefault(x => x.Dimension == d);
        return dim is null ? "—/2" : $"{(int)dim.Score}/2";
    }
}

public sealed record AiLevelReportPayload(string Markdown, IReadOnlyList<AiLevelSkillScore> Scores);
