using System.Text;
using HelpersSidecar.Domain;
using HelpersSidecar.Infrastructure;

namespace HelpersSidecar.Application;

/// <summary>
/// Builds the cross-domain INDEX of plans across every registered
/// <see cref="IDomain"/>. Plan-9's discoverability safety net — a
/// human reading the rendered <c>docs/INDEX.md</c> sees the entire
/// plan landscape (per-domain + cross-domain) in one file without
/// having to walk the directory tree by hand.
///
/// Pure function over a project root + the registered domains; the
/// scanner is injected so this composes the same multi-directory
/// walk that BR-EXTEND-011's <see cref="DomainImpactScope"/>
/// relies on.
/// </summary>
public sealed class PlansIndexBuilder
{
    private readonly IDomainResolver _domains;
    private readonly IPlanDirectoryScanner _scanner;

    public PlansIndexBuilder(IDomainResolver domains, IPlanDirectoryScanner scanner)
    {
        _domains = domains;
        _scanner = scanner;
    }

    /// <summary>
    /// Compose the markdown body. Output shape:
    ///
    /// <code>
    /// # Plans index
    ///
    /// > Auto-generated by /helpers/plans/index. Per BR-PROCESS-013
    /// > this is a schema-versioned report (PLAN_INDEX v1).
    ///
    /// PLAN_INDEX v1 — generated 2026-05-03T03:14:00Z
    ///
    /// ## Domain: otel (docs/otel/plans)
    /// - The-OTEL-Plan.md
    /// - The-OTEL-Plan-2-go-collector.md
    /// - …
    ///
    /// ## Domain: cross-domain (docs/cross-domain/plans)
    /// - (no plans yet)
    /// </code>
    /// </summary>
    public PlansIndexResult Build(string projectRoot, DateTimeOffset generatedAtUtc)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Plans index");
        sb.AppendLine();
        sb.AppendLine("> Auto-generated by `/helpers/plans/index`. Per `BR-PROCESS-013`");
        sb.AppendLine("> this is a schema-versioned report. Re-run the endpoint to refresh.");
        sb.AppendLine();
        sb.AppendLine($"PLAN_INDEX v1 — generated {generatedAtUtc:yyyy-MM-ddTHH:mm:ssZ}");
        sb.AppendLine();

        var perDomain = new Dictionary<string, IReadOnlyList<string>>(StringComparer.Ordinal);
        var totalPlans = 0;

        // Sorted domain order for deterministic output.
        foreach (var domain in _domains.All.OrderBy(d => d.Name, StringComparer.Ordinal))
        {
            var dir = ResolveDir(projectRoot, domain.PlanFiles.Directory);
            var allFiles = _scanner.ListPlanFileNames(dir);
            var matching = allFiles
                .Where(f => domain.PlanFiles.TryParse(f, out _, out _))
                .OrderBy(f => f, StringComparer.OrdinalIgnoreCase)
                .ToList();
            perDomain[domain.Name] = matching;
            totalPlans += matching.Count;

            sb.AppendLine($"## Domain: {domain.Name} (`{domain.PlanFiles.Directory}`)");
            sb.AppendLine();
            if (matching.Count == 0)
            {
                sb.AppendLine("- _(no plans yet)_");
            }
            else
            {
                foreach (var name in matching)
                    sb.AppendLine($"- [{name}]({domain.PlanFiles.Directory}/{name})");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"---");
        sb.AppendLine($"_Total plans across {_domains.All.Count} domain(s): {totalPlans}_");

        return new PlansIndexResult(
            Markdown: sb.ToString(),
            PerDomainCounts: perDomain.ToDictionary(kv => kv.Key, kv => kv.Value.Count),
            TotalPlans: totalPlans);
    }

    private static string ResolveDir(string projectRoot, string domainDir)
    {
        if (string.IsNullOrEmpty(domainDir) || domainDir == ".")
            return projectRoot;
        return Path.IsPathRooted(domainDir) ? domainDir : Path.Combine(projectRoot, domainDir);
    }
}

public sealed record PlansIndexResult(
    string Markdown,
    IReadOnlyDictionary<string, int> PerDomainCounts,
    int TotalPlans);
